# Generated by Django 4.2.7 on 2023-12-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quimun', '0002_rename_content_quimun_name_remove_quimun_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quimun',
            new_name='Cliente',
        ),
    ]
