# Generated by Django 4.2.7 on 2023-12-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quimun', '0003_rename_quimun_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('id_empresa', models.IntegerField()),
                ('costo_diario', models.IntegerField()),
                ('dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
